// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Werwolf",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Werwolf",
            targets: ["AppModule"],
            teamIdentifier: "SYNMT3VHZ7",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "QR Code Scanning")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/twostraws/CodeScanner", "2.1.1"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CodeScanner", package: "CodeScanner")
            ],
            path: "."
        )
    ]
)